const SET_CITY_CORONA_LIST = 'SET_CITY_CORONA_LIST';
const SET_TOTAL_CORONA_INFO = 'SET_TOTAL_CORONA_INFO';
const SET_WORLD_CORONA_LSIT = 'SET_WORLD_CORONA_LIST';
const SET_VACCINATION_INFO = 'SET_VACCINATION_INFO';
const SET_A_WEEK_AGO_CORONA_INFO = 'SET_A_WEEK_AGO_CORONA_INFO';
const SET_INC_DEC_CORONA_INFO = 'SET_INC_DEC_CORONA_INFO';

export {
  SET_CITY_CORONA_LIST,
  SET_TOTAL_CORONA_INFO,
  SET_WORLD_CORONA_LSIT,
  SET_VACCINATION_INFO,
  SET_A_WEEK_AGO_CORONA_INFO,
  SET_INC_DEC_CORONA_INFO,
};
