const SET_CITY_CORONA_LIST = 'SET_CITY_CORONA_LIST';
const SET_TOTAL_CORONA_LIST = 'SET_TOTAL_CORONA_LIST';
const SET_WORLD_CORONA_LSIT = 'SET_WORLD_CORONA_LIST';
const SET_VACCINATION_INFO = 'SET_VACCINATION_INFO';

export { SET_CITY_CORONA_LIST, SET_TOTAL_CORONA_LIST, SET_WORLD_CORONA_LSIT, SET_VACCINATION_INFO };
