const SET_CITY_CORONA_LIST = 'SET_CITY_CORONA_LIST';
const SET_TOTAL_CORONA_INFO = 'SET_TOTAL_CORONA_INFO';
const SET_WORLD_CORONA_LIST = 'SET_WORLD_CORONA_LIST';
const SET_TOTAL_VACCINATION_INFO = 'SET_TOTAL_VACCINATION_INFO';
const SET_A_WEEK_AGO_CORONA_INFO = 'SET_A_WEEK_AGO_CORONA_INFO';
const SET_KOREA_INC_DEC_CORONA_INFO = 'SET_KOREA_INC_DEC_CORONA_INFO';
const SET_TOTAL_WORLD_CORONA_INFO = 'SET_TOTAL_WORLD_CORONA_INFO';
const SET_DISASTER_CHARACTERS_LIST = 'SET_DISASTER_CHARACTERS_LIST';

export {
  SET_CITY_CORONA_LIST,
  SET_TOTAL_CORONA_INFO,
  SET_WORLD_CORONA_LIST,
  SET_TOTAL_VACCINATION_INFO,
  SET_A_WEEK_AGO_CORONA_INFO,
  SET_KOREA_INC_DEC_CORONA_INFO,
  SET_TOTAL_WORLD_CORONA_INFO,
  SET_DISASTER_CHARACTERS_LIST,
};
